import { createSlice } from "@reduxjs/toolkit";

const CourseNameSlice = createSlice({
  name: "CourseNameSlice",
  initialState: [
    {
      id: 1,
      coursename: "Data Structures",
      slug: "data-structures",
      topics: [
        { name: "Arrays", slug: "arrays" },
        { name: "Linked Lists", slug: "linked-lists" },
        { name: "Stacks", slug: "stacks" },
        { name: "Queues", slug: "queues" },
        { name: "Trees", slug: "trees" },
        { name: "Graphs", slug: "graphs" },
      ],
    },
    {
      id: 2,
      coursename: "Algorithms",
      slug: "algorithms",
      topics: [
        { name: "Sorting", slug: "sorting" },
        { name: "Searching", slug: "searching" },
        { name: "Dynamic Programming", slug: "dynamic-programming" },
        { name: "Greedy", slug: "greedy" },
        { name: "Divide and Conquer", slug: "divide-and-conquer" },
        { name: "Backtracking", slug: "backtracking" },
      ],
    },
    {
      id: 3,
      coursename: "Web Development",
      slug: "web-development",
      topics: [
        { name: "HTML", slug: "html" },
        { name: "CSS", slug: "css" },
        { name: "JavaScript", slug: "javascript" },
        { name: "React", slug: "react" },
        { name: "Node.js", slug: "node-js" },
        { name: "Express", slug: "express" },
      ],
    },
    {
      id: 4,
      coursename: "Database Management Systems",
      slug: "database-management-systems",
      topics: [
        { name: "Relational Algebra", slug: "relational-algebra" },
        { name: "SQL", slug: "sql" },
        { name: "Normalization", slug: "normalization" },
        { name: "Transactions", slug: "transactions" },
        { name: "Concurrency Control", slug: "concurrency-control" },
        { name: "NoSQL", slug: "nosql" },
      ],
    },
    {
      id: 5,
      coursename: "Operating Systems",
      slug: "operating-systems",
      topics: [
        { name: "Processes", slug: "processes" },
        { name: "Threads", slug: "threads" },
        { name: "Scheduling", slug: "scheduling" },
        { name: "Memory Management", slug: "memory-management" },
        { name: "Virtual Memory", slug: "virtual-memory" },
        { name: "File Systems", slug: "file-systems" },
      ],
    },
    {
      id: 6,
      coursename: "Computer Networks",
      slug: "computer-networks",
      topics: [
        { name: "OSI Model", slug: "osi-model" },
        { name: "TCP/IP Suite", slug: "tcp-ip-suite" },
        { name: "Routing Protocols", slug: "routing-protocols" },
        { name: "Application Layer", slug: "application-layer" },
        { name: "Transport Layer", slug: "transport-layer" },
        { name: "Network Security", slug: "network-security" },
      ],
    },
    {
      id: 7,
      coursename: "Machine Learning",
      slug: "machine-learning",
      topics: [
        { name: "Supervised Learning", slug: "supervised-learning" },
        { name: "Unsupervised Learning", slug: "unsupervised-learning" },
        { name: "Linear Regression", slug: "linear-regression" },
        { name: "Neural Networks", slug: "neural-networks" },
        { name: "SVM", slug: "svm" },
        { name: "Decision Trees", slug: "decision-trees" },
      ],
    },
    {
      id: 8,
      coursename: "Artificial Intelligence",
      slug: "artificial-intelligence",
      topics: [
        { name: "Search Algorithms", slug: "search-algorithms" },
        { name: "Knowledge Representation", slug: "knowledge-representation" },
        { name: "Logic", slug: "logic" },
        { name: "Planning", slug: "planning" },
        { name: "Expert Systems", slug: "expert-systems" },
        { name: "Computer Vision", slug: "computer-vision" },
      ],
    },
    {
      id: 9,
      coursename: "Software Engineering",
      slug: "software-engineering",
      topics: [
        { name: "SDLC Models", slug: "sdlc-models" },
        { name: "Agile Methodologies", slug: "agile-methodologies" },
        { name: "Requirements Engineering", slug: "requirements-engineering" },
        { name: "Software Design", slug: "software-design" },
        { name: "Testing", slug: "testing" },
        { name: "Maintenance", slug: "maintenance" },
      ],
    },
    {
      id: 10,
      coursename: "Discrete Mathematics",
      slug: "discrete-mathematics",
      topics: [
        { name: "Propositional Logic", slug: "propositional-logic" },
        { name: "Set Theory", slug: "set-theory" },
        { name: "Combinatorics", slug: "combinatorics" },
        { name: "Graph Theory", slug: "graph-theory" },
        { name: "Relations", slug: "relations" },
        { name: "Functions", slug: "functions" },
      ],
    },
    {
      id: 11,
      coursename: "Cloud Computing",
      slug: "cloud-computing",
      topics: [
        { name: "Virtualization", slug: "virtualization" },
        { name: "IaaS", slug: "iaas" },
        { name: "PaaS", slug: "paas" },
        { name: "SaaS", slug: "saas" },
        { name: "AWS Architecture", slug: "aws-architecture" },
        { name: "Docker & Kubernetes", slug: "docker-kubernetes" },
      ],
    },
    {
      id: 12,
      coursename: "Cybersecurity",
      slug: "cybersecurity",
      topics: [
        { name: "Cryptography", slug: "cryptography" },
        { name: "Network Security", slug: "network-security" },
        { name: "Ethical Hacking", slug: "ethical-hacking" },
        { name: "Malware Analysis", slug: "malware-analysis" },
        { name: "Risk Management", slug: "risk-management" },
        { name: "Forensics", slug: "forensics" },
      ],
    },
    {
      id: 13,
      coursename: "Mobile App Development",
      slug: "mobile-app-development",
      topics: [
        { name: "Android Basics", slug: "android-basics" },
        { name: "iOS Basics", slug: "ios-basics" },
        { name: "React Native", slug: "react-native" },
        { name: "Flutter", slug: "flutter" },
        { name: "State Management", slug: "state-management" },
        { name: "Publishing", slug: "publishing" },
      ],
    },
    {
      id: 14,
      coursename: "UI/UX Design",
      slug: "ui-ux-design",
      topics: [
        { name: "Design Thinking", slug: "design-thinking" },
        { name: "Wireframing", slug: "wireframing" },
        { name: "Prototyping", slug: "prototyping" },
        { name: "User Research", slug: "user-research" },
        { name: "Usability Testing", slug: "usability-testing" },
        { name: "Figma", slug: "figma" },
      ],
    },
    {
      id: 15,
      coursename: "Compiler Design",
      slug: "compiler-design",
      topics: [
        { name: "Lexical Analysis", slug: "lexical-analysis" },
        { name: "Syntax Analysis", slug: "syntax-analysis" },
        { name: "Semantic Analysis", slug: "semantic-analysis" },
        { name: "Intermediate Code", slug: "intermediate-code" },
        { name: "Code Optimization", slug: "code-optimization" },
        { name: "Code Generation", slug: "code-generation" },
      ],
    },
    {
      id: 16,
      coursename: "Distributed Systems",
      slug: "distributed-systems",
      topics: [
        { name: "Clock Synchronization", slug: "clock-synchronization" },
        { name: "Consensus Algorithms", slug: "consensus-algorithms" },
        { name: "Distributed File Systems", slug: "distributed-file-systems" },
        { name: "CAP Theorem", slug: "cap-theorem" },
        { name: "RPC", slug: "rpc" },
        { name: "MapReduce", slug: "mapreduce" },
      ],
    },
    {
      id: 17,
      coursename: "Computer Architecture",
      slug: "computer-architecture",
      topics: [
        {
          name: "Instruction Set Architecture",
          slug: "instruction-set-architecture",
        },
        { name: "Pipelining", slug: "pipelining" },
        { name: "Memory Hierarchy", slug: "memory-hierarchy" },
        { name: "Cache Coherence", slug: "cache-coherence" },
        { name: "Multicore Processors", slug: "multicore-processors" },
        { name: "I/O Systems", slug: "i-o-systems" },
      ],
    },
    {
      id: 18,
      coursename: "Cryptography",
      slug: "cryptography",
      topics: [
        { name: "Symmetric Encryption", slug: "symmetric-encryption" },
        { name: "Asymmetric Encryption", slug: "asymmetric-encryption" },
        { name: "Hash Functions", slug: "hash-functions" },
        { name: "Digital Signatures", slug: "digital-signatures" },
        { name: "PKI", slug: "pki" },
        { name: "Quantum Cryptography", slug: "quantum-cryptography" },
      ],
    },
    {
      id: 19,
      coursename: "Natural Language Processing",
      slug: "natural-language-processing",
      topics: [
        { name: "Text Preprocessing", slug: "text-preprocessing" },
        { name: "Word Embeddings", slug: "word-embeddings" },
        { name: "Sentiment Analysis", slug: "sentiment-analysis" },
        { name: "Named Entity Recognition", slug: "named-entity-recognition" },
        { name: "Machine Translation", slug: "machine-translation" },
        { name: "Transformers", slug: "transformers" },
      ],
    },
    {
      id: 20,
      coursename: "DevOps Engineering",
      slug: "devops-engineering",
      topics: [
        { name: "CI/CD Pipelines", slug: "ci-cd-pipelines" },
        { name: "Infrastructure as Code", slug: "infrastructure-as-code" },
        { name: "Configuration Management", slug: "configuration-management" },
        { name: "Monitoring & Logging", slug: "monitoring-logging" },
        { name: "GitOps", slug: "gitops" },
        { name: "Microservices", slug: "microservices" },
      ],
    },
  ],
});

export default CourseNameSlice;
export const CourseNameSliceactions = CourseNameSlice.actions;
